services:
  users:
    build: ./users
    volumes:
      - ./users:/node
      - "uploads:/node/files"
      - /node/node_modules
    environment:
      - BASE_URL=http://13.36.208.34:3003
      - LOGIN_URL=http://13.36.208.34:3003
      - SERVER_PORT=3000
      - DATABASE_URL=mongodb+srv://timosky:vFlB0wxQ3zwhx5Yz@cluster0.sxdyp28.mongodb.net/test
      - SECRET_KEY=9mODTPQzQz-zlXxU9RPwfg
      - EMAIL_PASSWORD=rchmlzwnhrgpmnpb
      - EMAIL_USERNAME=timsnoreplyautomatedbot@gmail.com
      - EMAIL_HOST=smtp.gmail.com
      - FROM_EMAIL=Knowledge Exchange System
    ports:
      - "3000:3000"
  institutes:
    build: ./research_institutes
    volumes:
      - ./research_institutes:/node
      - "uploads:/node/uploads"
      - /node/node_modules
    environment:
      - SERVER_PORT=3000
      - DATABASE_URL=mongodb+srv://timosky:vFlB0wxQ3zwhx5Yz@cluster0.sxdyp28.mongodb.net/test
      - USERS_SERVICE=http://users:3000/users
      - LOG_URL=http://users:3000/logs
      - MESSAGE_URL=http://users:3000/messages
    ports:
      - "3001:3000"
  resources:
    build: ./research_resources
    volumes:
      - ./research_resources:/node
      - "uploads:/node/uploads"
      - /node/node_modules
    environment:
      - DATABASE_URL=mongodb+srv://timosky:vFlB0wxQ3zwhx5Yz@cluster0.sxdyp28.mongodb.net/test
      - USERS_SERVICE=http://users:3000/users
      - INSTITUTE_SERVICE=http://institutes:3000/institutes
      - LOG_URL=http://users:3000/logs
    ports:
      - "3002:3000"
  frontend:
    build: ./project
    volumes:
      - ./project:/app
      - /app/node_modules
    environment:
      - REACT_APP_PORT=http://13.36.208.34
    ports:
      - "3003:80"
volumes:
  uploads:
