services:
  users:
    build: ./users
    volumes:
      - ./users:/node
      - "uploads:/node/files"
      - /node/node_modules
    environment:
      - BASE_URL=https://main.d6a2usqsag8oq.amplifyapp.com/
      - LOGIN_URL=https://main.d6a2usqsag8oq.amplifyapp.com/login
      - SERVER_PORT=3000
      - DATABASE_URL=mongodb+srv://kxcsadmnistrator:AbFvgEA6pjIxVuIl@application-cluster.xtdk5y0.mongodb.net/kxcscollection
      - SECRET_KEY=9mODTPQzQz-zlXxU9RPwfg
      - EMAIL_PASSWORD=olcybqohcmvbcykx
      - EMAIL_USERNAME=kxcsadmnistrator@gmail.com
      - EMAIL_HOST=smtp.gmail.com
      - FROM_EMAIL=Knowledge Exchange System
    ports:
      - "3000:3000"
  institutes:
    build: ./research_institutes
    volumes:
      - ./research_institutes:/node
      - "uploads:/node/uploads"
      - /node/node_modules
    environment:
      - SERVER_PORT=3000
      - DATABASE_URL=mongodb+srv://kxcsadmnistrator:AbFvgEA6pjIxVuIl@application-cluster.xtdk5y0.mongodb.net/kxcscollection
      - USERS_SERVICE=http://users:3000/users
      - LOG_URL=http://users:3000/logs
      - MESSAGE_URL=http://users:3000/messages
    ports:
      - "3001:3000"
  resources:
    build: ./research_resources
    volumes:
      - ./research_resources:/node
      - "uploads:/node/uploads"
      - /node/node_modules
    environment:
      - DATABASE_URL=mongodb+srv://kxcsadmnistrator:AbFvgEA6pjIxVuIl@application-cluster.xtdk5y0.mongodb.net/kxcscollection
      - USERS_SERVICE=http://users:3000/users
      - INSTITUTE_SERVICE=http://institutes:3000/institutes
      - LOG_URL=http://users:3000/logs
    ports:
      - "3002:3000"
volumes:
  uploads:
